includes:
  - configs/Experiment-2/metrics_and_losses.yml
  - configs/Experiment-2/dataset.yml




model:
  name: schnet
  hidden_channels: 1024
  num_filters: 256
  num_interactions: 5
  num_gaussians: 200
  cutoff: 6.0
  use_pbc: False
  otf_graph: True

optim:
  optimizer: Adam
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 313907
    - 523179
    - 732451
  warmup_steps: 209271
  warmup_factor: 0.2

  batch_size:                   8         # 6
  eval_batch_size:              8         # 6
  #  load_balancing: atoms # It must be commented for loading data without references.
  num_workers: 8
  max_epochs: 50
  eval_every: 1000

  scheduler: LambdaLR
  scheduler_params:
    lambda_type: cosine
    warmup_factor: 0.2
    warmup_epochs: 0.01
    lr_min_factor: 0.01         #
