trainer: equiformerv2_forces

dataset:
  train:
    format: ase_read_multi
    src: databases/overfit/train
    pattern: '*.traj'
    a2g_args:
      r_energy: true
      r_forces: true
    use_tqdm: true
    keep_in_memory: true
    key_mapping:
      atoms: "atomic_numbers"

  val:
    format: ase_read_multi
    src: databases/overfit/test
    pattern: '*.traj'
    a2g_args:
      r_energy: true
      r_forces: true
    use_tqdm: true
    keep_in_memory: true
    key_mapping:
      atoms: "atomic_numbers"
#
#  test:
#    format: ase_read_multi
#    src: databases/test
#    pattern: '*.traj'
#    a2g_args:
#      r_energy: true
#      r_forces: true
#    use_tqdm: true
#    keep_in_memory: true
#    key_mapping:
#      atoms: "atomic_numbers"
