includes:
  - configs/oc20/s2ef/all/dimenet_plus_plus/dpp.yml
#amp: true


dataset:
  train:
    format: ase_read_multi
    src: databases/train
    pattern: '*.traj'
    a2g_args:
      r_energy: true
      r_forces: true
    use_tqdm: true
    keep_in_memory: True
    key_mapping:
      atoms: "atomic_numbers"
  val:
    format: ase_read
    src: databases/val
    pattern: '*.traj'
    a2g_args:
      r_energy: true
      r_forces: true
    use_tqdm: true
    keep_in_memory: True
    key_mapping:
      atoms: "atomic_numbers"
  test:
    format: ase_read_multi
    src: databases/test
    pattern: '*.traj'
    a2g_args:
      r_energy: true
      r_forces: true
    use_tqdm: true
    keep_in_memory: True
    key_mapping:
      atoms: "atomic_numbers"

logger: wandb

loss_functions:
  - energy:
      fn: mae
      coefficient: 4
  - forces:
      fn: l2mae
      coefficient: 100

optim:
  batch_size: 8
  eval_batch_size: 8
  eval_every: 1
  num_workers: 8
  max_epochs: 100
