includes:
  - configs/Experiment-1-HO/metrics_and_losses.yml
  - configs/Experiment-1-HO/dataset.yml

model:
  name: gemnet_oc
  num_spherical: 7
  num_radial: 128
  num_blocks: 6
  emb_size_atom: 256
  emb_size_edge: 1024
  emb_size_trip_in: 64
  emb_size_trip_out: 128
  emb_size_quad_in: 64
  emb_size_quad_out: 32
  emb_size_aint_in: 64
  emb_size_aint_out: 64
  emb_size_rbf: 32
  emb_size_cbf: 16
  emb_size_sbf: 64
  num_before_skip: 2
  num_after_skip: 2
  num_concat: 4
  num_atom: 3
  num_output_afteratom: 3
  cutoff: 12.0
  cutoff_qint: 12.0
  cutoff_aeaint: 12.0
  cutoff_aint: 12.0
  max_neighbors: 30
  max_neighbors_qint: 8
  max_neighbors_aeaint: 20
  max_neighbors_aint: 1000
  rbf:
    name: gaussian
  envelope:
    name: polynomial
    exponent: 5
  cbf:
    name: spherical_harmonics
  sbf:
    name: legendre_outer
  extensive: True
  output_init: HeOrthogonal
  activation: silu
  scale_file: configs/oc20/s2ef/all/gemnet/scaling_factors/gemnet-oc-large.pt

  regress_forces: True
  direct_forces: True
  forces_coupled: False

  quad_interaction: True
  atom_edge_interaction: True
  edge_atom_interaction: True
  atom_interaction: True

  num_atom_emb_layers: 2
  num_global_out_layers: 2
  qint_tags: [1, 2]
  otf_graph: True

optim:
  batch_size: 8
  eval_batch_size: 8
#  load_balancing: atoms
  eval_every: 1000
  num_workers: 2
  lr_initial: 2.e-4
  optimizer: AdamW
  optimizer_params:
    amsgrad: True
    weight_decay: 0.
  scheduler: ReduceLROnPlateau
  scheduler_params:
    lambda_type: cosine
    warmup_factor: 0.2
    warmup_epochs: 0.01
    lr_min_factor: 0.01
  mode: min
  factor: 0.8
  patience: 3
  max_epochs: 50
#  force_coefficient: 100
#  energy_coefficient: 1
  ema_decay: 0.999
  clip_grad_norm: 10
