trainer: equiformerv2_forces


dataset:
  train:
    format: ase_read_multi
    src: databases/train
    pattern: '*.traj'
    a2g_args:
      r_energy: true
      r_forces: true
    use_tqdm: true
    keep_in_memory: True
    key_mapping:
      atoms: "atomic_numbers"
  val:
    format: ase_read_multi
    src: databases/val
    pattern: '*.traj'
    a2g_args:
      r_energy: true
      r_forces: true
    use_tqdm: true
    keep_in_memory: True
    key_mapping:
      atoms: "atomic_numbers"
  test:
    format: ase_read_multi
    src: databases/test
    pattern: '*.traj'
    a2g_args:
      r_energy: true
      r_forces: true
    use_tqdm: true
    keep_in_memory: True
    key_mapping:
      atoms: "atomic_numbers"

logger: wandb

outputs:
  energy:
    property: energy
    shape: 1
    level: system
  forces:
    property: forces
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 4
  - forces:
      fn: l2mae
      coefficient: 100

evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae

hide_eval_progressbar: False


model:
  name: gp_gemnet_t
  num_spherical: 7
  num_radial: 128
  num_blocks: 3
  emb_size_atom: 512
  emb_size_edge: 512
  emb_size_trip: 64
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_bil_trip: 64
  num_before_skip: 1
  num_after_skip: 2
  num_concat: 1
  num_atom: 3
  cutoff: 6.0
  max_neighbors: 50
  rbf:
    name: gaussian
  envelope:
    name: polynomial
    exponent: 5
  cbf:
    name: spherical_harmonics
  extensive: True
  otf_graph: False
  output_init: HeOrthogonal
  activation: silu
  scale_file: configs/oc20/s2ef/all/gp_gemnet/scaling_factors/gemnet-dT.json

  regress_forces: True
  direct_forces: True

optim:
  batch_size: 8
  eval_batch_size: 8
  eval_every: 1
  num_workers: 8
  lr_initial: 5.e-4
  optimizer: AdamW
  optimizer_params: {"amsgrad": True}
  scheduler: ReduceLROnPlateau
  mode: min
  factor: 0.8
  patience: 3
  max_epochs: 100
  force_coefficient: 100
  energy_coefficient: 1
  ema_decay: 0.999
  clip_grad_norm: 10
