trainer: equiformerv2_forces


dataset:
  train:
    format: ase_read_multi
    src: databases/train
    pattern: '*.traj'
    a2g_args:
      r_energy: true
      r_forces: true
    use_tqdm: true
    keep_in_memory: True
    key_mapping:
      atoms: "atomic_numbers"
  val:
    format: ase_read_multi
    src: databases/val
    pattern: '*.traj'
    a2g_args:
      r_energy: true
      r_forces: true
    use_tqdm: true
    keep_in_memory: True
    key_mapping:
      atoms: "atomic_numbers"
  test:
    format: ase_read_multi
    src: databases/test
    pattern: '*.traj'
    a2g_args:
      r_energy: true
      r_forces: true
    use_tqdm: true
    keep_in_memory: True
    key_mapping:
      atoms: "atomic_numbers"

logger: wandb

outputs:
  energy:
    property: energy
    shape: 1
    level: system
  forces:
    property: forces
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 4
  - forces:
      fn: l2mae
      coefficient: 100

evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae

hide_eval_progressbar: False


model:
  name: painn
  hidden_channels: 512
  num_layers: 6
  num_rbf: 128
  cutoff: 12.0
  max_neighbors: 50
  scale_file: configs/oc20/s2ef/all/painn/painn_nb6_scaling_factors.pt
  regress_forces: True
  direct_forces: True
  use_pbc: False

optim:
  batch_size: 8
  eval_batch_size: 8
#  load_balancing: atoms
  eval_every: 1
  num_workers: 8
  optimizer: AdamW
  optimizer_params:
    amsgrad: True
    weight_decay: 0.  # 2e-6 (TF weight decay) / 1e-4 (lr) = 2e-2
  lr_initial: 1.e-4
  lr_gamma: 0.8
  scheduler: ReduceLROnPlateau
  mode: min
  factor: 0.8
  patience: 3
  max_epochs: 100
  force_coefficient: 100
  energy_coefficient: 1
  ema_decay: 0.999
  clip_grad_norm: 10