includes:
  - configs/reasoning/metrics_and_losses.yml
  - configs/reasoning/dataset.yml

model:
  name: escn
  num_layers: 20
  max_neighbors: 20
  cutoff: 12.0
  sphere_channels: 160
  hidden_channels: 384
  lmax_list: [6]
  mmax_list: [3]
  num_sphere_samples: 128
  distance_function: "gaussian"
  regress_forces: True
  use_pbc: False
  basis_width_scalar: 2.0
  otf_graph: True

optim:
  batch_size: 3
  eval_batch_size: 1
  num_workers: 8
  lr_initial: 0.0008
  optimizer: AdamW
  optimizer_params: {"amsgrad": True}
  eval_every: 2500
  lr_gamma: 0.3
  lr_milestones: # epochs at which lr_initial <- lr_initial * lr_gamma
    - 433166
    - 541460
    - 649750
  warmup_steps: 100
  warmup_factor: 0.2
  max_epochs: 100
  scheduler: LambdaLR
  scheduler_params:
    lambda_type: cosine
    warmup_factor: 0.2
    warmup_epochs: 0.01
    lr_min_factor: 0.01
  clip_grad_norm: 20
  ema_decay: 0.999
