includes:
  - configs/Experiment-4/metrics_and_losses.yml
  - configs/Experiment-4/dataset.yml


model:
  name: equiformer_v2

  use_pbc:                  True
  regress_forces:           True
  otf_graph:                True
  max_neighbors:            20
  max_radius:               12.0
  max_num_elements:         90

  num_layers:               8
  sphere_channels:          64
  attn_hidden_channels:     64              # [64, 96] This determines the hidden size of message passing. Do not necessarily use 96.
  num_heads:                8
  attn_alpha_channels:      64              # Not used when `use_s2_act_attn` is True.
  attn_value_channels:      16
  ffn_hidden_channels:      64
  norm_type:                'layer_norm_sh' # ['rms_norm_sh', 'layer_norm', 'layer_norm_sh']

  lmax_list:                [4]
  mmax_list:                [2]
  grid_resolution:          18              # [18, 16, 14, None] For `None`, simply comment this line.

  num_sphere_samples:       64

  edge_channels:            64
  use_atom_edge_embedding:  True
  distance_function:        'gaussian'
  num_distance_basis:       512         # not used

  attn_activation:          'silu'
  use_s2_act_attn:          False       # [False, True] Switch between attention after S2 activation or the original EquiformerV1 attention.
  ffn_activation:           'silu'      # ['silu', 'swiglu']
  use_gate_act:             False       # [False, True] Switch between gate activation and S2 activation
  use_grid_mlp:             True        # [False, True] If `True`, use projecting to grids and performing MLPs for FFNs.

  alpha_drop:               0.1         # [0.0, 0.1]
  drop_path_rate:           0.1         # [0.0, 0.05]
  proj_drop:                0.0

  weight_init:              'uniform'    # ['uniform', 'normal']

optim:
  lr_initial:                   0.0004    # [0.0002, 0.0004], eSCN uses 0.0008 for batch size 96

  optimizer: AdamW
  optimizer_params:
    weight_decay: 0.001
  scheduler: LambdaLR
  scheduler_params:
    lambda_type: cosine
    warmup_factor: 0.2
    warmup_epochs: 0.01
    lr_min_factor: 0.01         #

  clip_grad_norm: 100
  ema_decay: 0.999

  batch_size:                   8         # 6
  eval_batch_size:              8         # 6
  #  load_balancing: atoms # It must be commented for loading data without references.
  num_workers: 8
  max_epochs: 50
  eval_every: 1000
