includes:
  - configs/Experiment-1/metrics_and_losses.yml
  - configs/Experiment-1/dataset.yml


model:
  name: dimenetplusplus
  hidden_channels: 256
  out_emb_channels: 192
  num_blocks: 3
  cutoff: 6.0
  num_radial: 6
  num_spherical: 7
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  regress_forces: True
  use_pbc: False

# *** Important note ***
#   The total number of gpus used for this run was 256.
#   If the global batch size (num_gpus * batch_size) is modified
#   the lr_milestones and warmup_steps need to be adjusted accordingly.

optim:
  batch_size: 8
  eval_batch_size: 8
  eval_every: 10000
  num_workers: 8
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 174393
    - 348786
    - 523179
  warmup_steps: 174393
  warmup_factor: 0.2
  max_epochs: 50


  scheduler: LambdaLR
  scheduler_params:
    lambda_type: cosine
    warmup_factor: 0.2
    warmup_epochs: 0.01
    lr_min_factor: 0.01         #