includes:
  - configs/Experiment-3/metrics_and_losses.yml
  - configs/Experiment-3/dataset.yml


model:
  name: painn
  hidden_channels: 256
  num_layers: 6
  num_rbf: 128
  cutoff: 12.0
  max_neighbors: 50
  scale_file: configs/oc20/s2ef/all/painn/painn_nb6_scaling_factors.pt
  regress_forces: True
  direct_forces: True
  use_pbc: False
  otf_graph: True

optim:
  batch_size: 8
  eval_batch_size: 8
#  load_balancing: atoms
  eval_every: 1000
  num_workers: 8
  optimizer: AdamW
  optimizer_params:
    amsgrad: True
    weight_decay: 0.  # 2e-6 (TF weight decay) / 1e-4 (lr) = 2e-2
  lr_initial: 1.e-4
  lr_gamma: 0.8
  scheduler: ReduceLROnPlateau
  scheduler_params:
    lambda_type: cosine
    warmup_factor: 0.2
    warmup_epochs: 0.01
    lr_min_factor: 0.01
  mode: min
  factor: 0.8
  patience: 3
  max_epochs: 50
#  force_coefficient: 100
#  energy_coefficient: 1
  ema_decay: 0.999
  clip_grad_norm: 10
